input_data:
  cisTopic_obj_fname: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/cistopic_obj.pkl"
  GEX_anndata_fname: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/adata.h5ad"
  menr_fname: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/menr.pkl"

output_data:
  # output for prepare_GEX_ACC
  combined_GEX_ACC_mudata: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/ACC_GEX.h5mu"
  # output for prepare_menr
  cistromes_direct: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/cistromes_direct.h5ad"
  cistromes_extended: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/cistromes_extended.h5ad"
  tf_names: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/tf_names.txt"
  # output for download_genome_annotations
  genome_annotation: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/genome_annotation.tsv"
  chromsizes: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/chromsizes.tsv"
  # output for search_space
  search_space: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/search_space.tsv"
  # output tf_to_gene
  tf_to_gene_adjacencies: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/tf_to_gene_adj.tsv"
  # output region_to_gene
  region_to_gene_adjacencies: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/region_to_gene_adj.tsv"
  # output eGRN
  eRegulons_direct: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/eRegulon_direct.tsv"
  eRegulons_extended: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/eRegulons_extended.tsv"
  # output AUCell
  AUCell_direct: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/AUCell_direct.h5mu"
  AUCell_extended: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/AUCell_extended.h5mu"

params_general:
  temp_dir: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli"
  n_cpu: 40
  seed: 666

params_data_preparation:
  # Params for prepare_GEX_ACC
  bc_transform_func: "\"lambda x: f'{x}-10x_pbmc'\""
  is_multiome: True
  key_to_group_by: ""
  nr_cells_per_metacells: 10
  # Params for prepare_menr
  direct_annotation: "Direct_annot"
  extended_annotation: "Orthology_annot"
  # Params for download_genome_annotations
  species: "hsapiens"
  biomart_host: "http://www.ensembl.org"
  # Params for search_space
  search_space_upstream: "1000 150000"
  search_space_downstream: "1000 150000"
  search_space_extend_tss: "10 10"

params_inference:
  # Params for tf_to_gene
  tf_to_gene_importance_method: "GBM"
  # Params regions_to_gene
  region_to_gene_importance_method: "GBM"
  region_to_gene_correlation_method: "SR"
  # Params for eGRN inference
  order_regions_to_genes_by: "importance"
  order_TFs_to_genes_by: "importance"
  gsea_n_perm: 1000
  quantile_thresholds_region_to_gene: "0.85 0.90 0.95"
  top_n_regionTogenes_per_gene: "5 10 15"
  top_n_regionTogenes_per_region: ""
  min_regions_per_gene: 0
  rho_threshold: 0.05
  min_target_genes: 10

