input_data:
  cisTopic_obj_fname: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/cistopic_obj.pkl"
  GEX_anndata_fname: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/adata.h5ad"

params:
  bc_transform_func: "\"lambda x: f'{x}-10x_pbmc'\""

output_data:
  combined_GEX_ACC_mudata: "/data/users/sdewin/PhD/python_modules/scenicplus/tests/test_cli/ACC_GEX.h5mu"